import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { openDatabase } from '../backend/db.js';
import { save } from '../backend/resources.js';
import { createProviderConnections } from '../backend/provider-connections.js';
import { migrateCloudOwner } from '../scripts/migrate-cloud-owner.js';

test('Offline owner migration preserves records, original bytes, keys and queue rows without changing source',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'openfunnel-migration-'));
  t.after(()=>rm(dir,{recursive:true,force:true}));
  const sourcePath=join(dir,'legacy.sqlite'), cloudDirectory=join(dir,'cloud');
  const env={PROVIDER_ENCRYPTION_KEY:'ab'.repeat(32),CLOUD_OWNER_EMAIL:'owner@example.com'};
  const old=openDatabase(sourcePath);
  const contact=save(old,'contacts',{name:'Legacy contact'});
  const agent=save(old,'ai_agents',{name:'Legacy agent'});
  const stamp=new Date().toISOString();
  const channel=save(old,'channels',{name:'Legacy channel',kind:'manual'});
  const conversation=save(old,'conversations',{title:'Legacy conversation',contact_id:contact.id,channel_id:channel.id});
  const message=save(old,'messages',{conversation_id:conversation.id,body:'Pending reply',direction:'outgoing',occurred_at:stamp});
  old.prepare("INSERT INTO outbound_messages(id,message_id,conversation_id,revision,status,available_at,created_at,updated_at) VALUES (?,?,?,0,'pending',?,?,?)").run('pending-out',message.id,conversation.id,stamp,stamp,stamp);
  old.prepare("INSERT INTO api_keys(id,name,prefix,secret_hash,scopes,created_at,expires_at) VALUES (?,?,?,?,?,?,?)").run('legacy-key','Automation','of_example','synthetic-hash','["resources:read"]',stamp,'2099-01-01T00:00:00.000Z');
  old.prepare("INSERT INTO agent_documents (id,ai_agent_id,filename,media_type,size,original,extracted_text,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'ready',?,?)").run('doc',agent.id,'example.txt','text/plain',8,Buffer.from('original'),'original',stamp,stamp);
  createProviderConnections(old,env).save('zernio',{expected_version:0,apiKey:'migrated-secret'});
  old.prepare("UPDATE outbound_messages SET status='pending' WHERE id='pending-out'").run();
  const count=old.prepare('SELECT count(*) n FROM schema_migrations').get().n;
  old.close();
  const control=openDatabase(join(cloudDirectory,'control.sqlite'));
  const workspace=randomUUID();
  control.prepare('INSERT INTO auth_user(id,name,email,emailVerified,createdAt,updatedAt) VALUES (?,?,?,?,?,?)').run('owner','Owner','owner@example.com',1,Date.now(),Date.now());
  control.prepare("INSERT INTO cloud_accounts VALUES (?,?,'superadmin','active',?)").run('owner',workspace,stamp);
  control.close();
  const result=await migrateCloudOwner({sourcePath,cloudDirectory,env});
  const copied=openDatabase(result.destination);
  assert.equal(copied.prepare('SELECT name FROM contacts WHERE id=?').get(contact.id).name,'Legacy contact');
  assert.deepEqual(Buffer.from(copied.prepare('SELECT original FROM agent_documents WHERE id=?').get('doc').original),Buffer.from('original'));
  assert.equal(createProviderConnections(copied,{...env,APP_MODE:'cloud'},workspace).env.ZERNIO_API_KEY,'migrated-secret');
  assert.equal(copied.prepare('SELECT count(*) n FROM auth_user').get().n,0);
  assert.equal(copied.prepare('SELECT status FROM outbound_messages WHERE id=?').get('pending-out').status,'cancelled');
  assert.equal(copied.prepare('SELECT secret_hash FROM api_keys WHERE id=?').get('legacy-key').secret_hash,'synthetic-hash');
  copied.close();
  const original=openDatabase(sourcePath);
  assert.equal(original.prepare('SELECT count(*) n FROM schema_migrations').get().n,count);
  assert.equal(createProviderConnections(original,env).env.ZERNIO_API_KEY,'migrated-secret');
  assert.equal(original.prepare('SELECT status FROM outbound_messages WHERE id=?').get('pending-out').status,'pending');
  original.close();
  await assert.rejects(migrateCloudOwner({sourcePath,cloudDirectory,env}),/no creado/);
});
