CREATE TABLE users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE contacts (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT, phone TEXT, company TEXT, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE channels (id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL, description TEXT, external_reference TEXT, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE prompts (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, content TEXT NOT NULL, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE tools (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL, kind TEXT NOT NULL, input_schema TEXT CHECK(input_schema IS NULL OR (json_valid(input_schema) AND json_type(input_schema) = 'object')), active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE ai_agents (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, provider TEXT, model TEXT, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE agent_prompts (ai_agent_id TEXT NOT NULL REFERENCES ai_agents(id), prompt_id TEXT NOT NULL REFERENCES prompts(id), position INTEGER NOT NULL, PRIMARY KEY(ai_agent_id,prompt_id), UNIQUE(ai_agent_id,position));
CREATE TABLE agent_tools (ai_agent_id TEXT NOT NULL REFERENCES ai_agents(id), tool_id TEXT NOT NULL REFERENCES tools(id), PRIMARY KEY(ai_agent_id,tool_id));
CREATE TABLE pipelines (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE pipeline_stages (id TEXT PRIMARY KEY, pipeline_id TEXT NOT NULL REFERENCES pipelines(id), name TEXT NOT NULL, description TEXT, position INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(pipeline_id,name), UNIQUE(pipeline_id,position), UNIQUE(id,pipeline_id));
CREATE TABLE conversations (id TEXT PRIMARY KEY, title TEXT NOT NULL, contact_id TEXT NOT NULL REFERENCES contacts(id), channel_id TEXT NOT NULL REFERENCES channels(id), assigned_user_id TEXT REFERENCES users(id), ai_agent_id TEXT REFERENCES ai_agents(id), status TEXT NOT NULL CHECK(status IN ('open','closed')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(id,contact_id));
CREATE TABLE messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id), body TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN ('incoming','outgoing')), occurred_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE tickets (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT, contact_id TEXT NOT NULL REFERENCES contacts(id), pipeline_id TEXT NOT NULL REFERENCES pipelines(id), stage_id TEXT NOT NULL, conversation_id TEXT UNIQUE, assigned_user_id TEXT REFERENCES users(id), status TEXT NOT NULL CHECK(status IN ('open','closed')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(stage_id,pipeline_id) REFERENCES pipeline_stages(id,pipeline_id), FOREIGN KEY(conversation_id,contact_id) REFERENCES conversations(id,contact_id));
CREATE INDEX messages_conversation ON messages(conversation_id,occurred_at,id);
CREATE INDEX conversations_contact ON conversations(contact_id);
CREATE INDEX conversations_channel ON conversations(channel_id);
CREATE INDEX conversations_user ON conversations(assigned_user_id);
CREATE INDEX conversations_agent ON conversations(ai_agent_id);
CREATE INDEX tickets_contact ON tickets(contact_id);
CREATE INDEX tickets_stage ON tickets(stage_id,pipeline_id);
CREATE INDEX tickets_user ON tickets(assigned_user_id);
CREATE INDEX agent_prompts_prompt ON agent_prompts(prompt_id);
CREATE INDEX agent_tools_tool ON agent_tools(tool_id);
