ALTER TABLE channels ADD COLUMN provider TEXT;
ALTER TABLE channels ADD COLUMN external_profile_id TEXT;
ALTER TABLE channels ADD COLUMN external_account_id TEXT;
ALTER TABLE channels ADD COLUMN connection_status TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE channels ADD COLUMN default_ai_agent_id TEXT REFERENCES ai_agents(id);
ALTER TABLE channels ADD COLUMN automation_enabled INTEGER NOT NULL DEFAULT 0 CHECK(automation_enabled IN (0,1));
ALTER TABLE channels ADD COLUMN automation_enabled_at TEXT;
ALTER TABLE channels ADD COLUMN last_synced_at TEXT;
ALTER TABLE channels ADD COLUMN inbox_verified_at TEXT;
ALTER TABLE channels ADD COLUMN sync_error TEXT;
CREATE UNIQUE INDEX channels_external ON channels(provider,external_account_id) WHERE external_account_id IS NOT NULL;
ALTER TABLE conversations ADD COLUMN external_id TEXT;
ALTER TABLE conversations ADD COLUMN automation_mode TEXT NOT NULL DEFAULT 'manual' CHECK(automation_mode IN ('manual','automatic'));
ALTER TABLE conversations ADD COLUMN pause_reason TEXT;
ALTER TABLE conversations ADD COLUMN last_incoming_at TEXT;
ALTER TABLE conversations ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE conversations ADD COLUMN thread_control TEXT NOT NULL DEFAULT 'app';
ALTER TABLE conversations ADD COLUMN is_group INTEGER NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX conversations_external ON conversations(channel_id,external_id) WHERE external_id IS NOT NULL;
ALTER TABLE messages ADD COLUMN external_id TEXT;
ALTER TABLE messages ADD COLUMN source TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE messages ADD COLUMN delivery_status TEXT;
ALTER TABLE messages ADD COLUMN agent_run_id TEXT;
ALTER TABLE messages ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN has_attachments INTEGER NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX messages_external ON messages(conversation_id,external_id) WHERE external_id IS NOT NULL;
CREATE TABLE contact_identities (id TEXT PRIMARY KEY,contact_id TEXT NOT NULL REFERENCES contacts(id),channel_id TEXT NOT NULL REFERENCES channels(id),external_id TEXT NOT NULL,UNIQUE(channel_id,external_id));
CREATE TABLE connection_attempts (nonce TEXT PRIMARY KEY,session_hash TEXT NOT NULL,platform TEXT NOT NULL,profile_id TEXT NOT NULL,channel_id TEXT REFERENCES channels(id),expires_at TEXT NOT NULL);
CREATE TABLE integration_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE sync_jobs (id TEXT PRIMARY KEY,channel_id TEXT NOT NULL REFERENCES channels(id),conversation_id TEXT REFERENCES conversations(id),cursor TEXT,status TEXT NOT NULL DEFAULT 'pending',error TEXT,updated_at TEXT NOT NULL);
CREATE TABLE webhook_events (id TEXT PRIMARY KEY,event TEXT NOT NULL,payload TEXT,channel_id TEXT REFERENCES channels(id),conversation_id TEXT REFERENCES conversations(id),status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,error TEXT,received_at TEXT NOT NULL,processed_at TEXT);
CREATE TABLE model_validations (fingerprint TEXT PRIMARY KEY,model TEXT NOT NULL,validated_at TEXT NOT NULL);
CREATE TABLE agent_runs (id TEXT PRIMARY KEY,conversation_id TEXT NOT NULL REFERENCES conversations(id),trigger_message_id TEXT NOT NULL UNIQUE REFERENCES messages(id),ai_agent_id TEXT REFERENCES ai_agents(id),model TEXT,prompt_snapshot TEXT,status TEXT NOT NULL DEFAULT 'pending',revision INTEGER NOT NULL,config_hash TEXT,attempts INTEGER NOT NULL DEFAULT 0,available_at TEXT NOT NULL,usage TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE tool_runs (id TEXT PRIMARY KEY,agent_run_id TEXT NOT NULL REFERENCES agent_runs(id),call_id TEXT NOT NULL,name TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,arguments TEXT,result TEXT,status TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(agent_run_id,call_id));
CREATE TABLE outbound_messages (id TEXT PRIMARY KEY,message_id TEXT NOT NULL UNIQUE REFERENCES messages(id),conversation_id TEXT NOT NULL REFERENCES conversations(id),agent_run_id TEXT REFERENCES agent_runs(id),revision INTEGER NOT NULL,config_hash TEXT,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,available_at TEXT NOT NULL,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX webhook_work ON webhook_events(status,received_at);
CREATE INDEX agent_work ON agent_runs(status,available_at);
CREATE INDEX outbound_work ON outbound_messages(status,available_at);
