// Campos compartidos por validación del servidor y formularios de la app.
const text = (key, label, required = false, max = 160) => ({
  key,
  label,
  type: 'text',
  required,
  max,
});
const area = (key, label, required = false, max = 4000) => ({
  ...text(key, label, required, max),
  type: 'textarea',
});
const ref = (key, label, resource, required = false) => ({
  key,
  label,
  type: 'reference',
  resource,
  required,
});
const active = {
  key: 'active',
  label: 'Activo',
  type: 'boolean',
  default: true,
};
const state = {
  key: 'status',
  label: 'Estado',
  type: 'select',
  options: [
    ['open', 'Abierto'],
    ['closed', 'Cerrado'],
  ],
  default: 'open',
  required: true,
};
export const resources = {
  conversations: {
    label: 'Conversaciones',
    singular: 'conversación',
    group: 'Operación',
    title: 'title',
    search: ['title'],
    filters: ['contact_id', 'channel_id', 'assigned_user_id', 'status', 'automation_mode'],
    fields: [
      text('title', 'Título', true),
      ref('contact_id', 'Contacto', 'contacts', true),
      ref('channel_id', 'Canal', 'channels', true),
      ref('assigned_user_id', 'Responsable', 'users'),
      ref('ai_agent_id', 'Agente IA', 'ai_agents'),
      {
        key: 'automation_mode',
        label: 'Atención',
        type: 'select',
        readOnly: true,
        options: [
          ['manual', 'Manual'],
          ['automatic', 'Automática'],
        ],
      },
      state,
    ],
  },
  tickets: {
    label: 'Tickets',
    singular: 'ticket',
    group: 'Operación',
    title: 'title',
    search: ['title', 'description'],
    filters: [
      'contact_id',
      'assigned_user_id',
      'pipeline_id',
      'stage_id',
      'status',
      'conversation_id',
    ],
    fields: [
      text('title', 'Título', true),
      area('description', 'Descripción'),
      ref('contact_id', 'Contacto', 'contacts', true),
      ref('pipeline_id', 'Pipeline', 'pipelines', true),
      ref('stage_id', 'Etapa', 'pipeline_stages', true),
      ref('conversation_id', 'Conversación', 'conversations'),
      ref('assigned_user_id', 'Responsable', 'users'),
      state,
    ],
  },
  contacts: {
    label: 'Contactos',
    singular: 'contacto',
    group: 'Operación',
    title: 'name',
    search: ['name', 'email', 'phone'],
    filters: [],
    fields: [
      text('name', 'Nombre', true),
      { ...text('email', 'Email', false, 254), type: 'email' },
      text('phone', 'Teléfono', false, 80),
      text('company', 'Empresa'),
      area('notes', 'Notas'),
    ],
  },
  channels: {
    label: 'Canales',
    singular: 'canal',
    group: 'Configuración',
    note: 'Gestiona tus canales de Instagram y WhatsApp.',
    title: 'name',
    search: ['name', 'kind'],
    filters: ['kind', 'active'],
    fields: [
      text('name', 'Nombre', true),
      text('kind', 'Tipo', true),
      area('description', 'Descripción'),
      text('external_reference', 'Referencia externa', false, 255),
      active,
    ],
  },
  pipelines: {
    label: 'Pipelines',
    singular: 'pipeline',
    group: 'Configuración',
    title: 'name',
    search: ['name'],
    filters: ['active'],
    fields: [text('name', 'Nombre', true), area('description', 'Descripción'), active],
  },
  ai_agents: {
    label: 'Agentes IA',
    singular: 'agente IA',
    group: 'Configuración',
    note: 'Configura sus instrucciones, añade conocimiento y prueba sus respuestas.',
    title: 'name',
    search: ['name', 'description'],
    filters: ['active'],
    fields: [
      text('name', 'Nombre', true),
      area('description', 'Descripción'),
      active,
    ],
  },
  prompts: {
    label: 'Prompts',
    singular: 'prompt',
    group: 'Configuración',
    navigationParent: 'ai_agents',
    title: 'name',
    search: ['name', 'description'],
    filters: ['active'],
    fields: [
      text('name', 'Nombre', true),
      area('description', 'Descripción'),
      area('content', 'Instrucciones', true, 20000),
      active,
    ],
  },
  tools: {
    label: 'Tools',
    singular: 'tool',
    group: 'Configuración',
    navigationParent: 'ai_agents',
    readOnly: true,
    note: 'Herramientas nativas de OpenFunnel. Selecciona las que puede usar cada agente desde su pestaña Herramientas.',
    title: 'name',
    search: ['name', 'description'],
    filters: ['kind', 'active'],
    fields: [
      text('name', 'Nombre', true),
      area('description', 'Descripción', true),
      text('kind', 'Tipo', true),
      {
        ...area('input_schema', 'Esquema de entrada (objeto JSON)', false, 20000),
        type: 'json',
      },
      active,
    ],
  },
  users: {
    label: 'Usuarios',
    singular: 'usuario',
    group: 'Configuración',
    note: 'Personas para asignación; estos registros no habilitan acceso.',
    title: 'name',
    search: ['name', 'email'],
    filters: ['active'],
    fields: [
      text('name', 'Nombre', true),
      { ...text('email', 'Email', false, 254), type: 'email' },
      active,
    ],
  },
  messages: {
    label: 'Mensajes',
    singular: 'mensaje',
    title: 'body',
    search: ['body'],
    filters: ['conversation_id', 'direction'],
    fields: [
      ref('conversation_id', 'Conversación', 'conversations', true),
      area('body', 'Mensaje', true, 20000),
      {
        key: 'direction',
        label: 'Dirección',
        type: 'select',
        options: [
          ['incoming', 'Entrada'],
          ['outgoing', 'Salida'],
        ],
        required: true,
        default: 'incoming',
      },
      { key: 'occurred_at', label: 'Fecha', type: 'datetime', required: true },
    ],
  },
  pipeline_stages: {
    label: 'Etapas',
    singular: 'etapa',
    title: 'name',
    search: ['name'],
    filters: ['pipeline_id'],
    fields: [
      ref('pipeline_id', 'Pipeline', 'pipelines', true),
      text('name', 'Nombre', true),
      area('description', 'Descripción'),
      { key: 'position', label: 'Orden', type: 'integer', required: true },
    ],
  },
};
export const resourceEntries = Object.entries(resources).filter(
  ([, r]) => r.group && !r.navigationParent,
);
